name: release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    env:
      RELEASE_VERSION: 1
      DOCKERHUB_REPO_NAME: python-builder

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        env:
          IMG: ${{ github.repository_owner }}/${{ env.DOCKERHUB_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          LATEST_IMG: ${{ github.repository_owner }}/${{ env.DOCKERHUB_REPO_NAME }}:latest
        run: docker build -t ${{ env.IMG }} -t ${{ env.LATEST_IMG }} .

      - name: Push image to the Dockerhub
        env:
          IMG: ${{ github.repository_owner }}/${{ env.DOCKERHUB_REPO_NAME }}:${{ env.RELEASE_VERSION }}
          LATEST_IMG: ${{ github.repository_owner }}/${{ env.DOCKERHUB_REPO_NAME }}:latest
        run: docker push ${{ env.IMG }} && docker push ${{ env.LATEST_IMG }}
